"""initial

Revision ID: da314c11d9e9
Revises: 
Create Date: 2021-08-30 17:50:41.313069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da314c11d9e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('auth_user_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parent', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kas_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kas_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('kas_type', sa.Enum('operational', 'pembangunan', name='kasenum'), nullable=True),
    sa.Column('kas_legder_id', sa.Integer(), nullable=True),
    sa.Column('journal_date', sa.Date(), nullable=True),
    sa.Column('debit', sa.Float(precision=17), nullable=True),
    sa.Column('credit', sa.Float(precision=17), nullable=True),
    sa.Column('balance', sa.Float(precision=17), nullable=True),
    sa.ForeignKeyConstraint(['kas_legder_id'], ['kas_ledger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kas_journal')
    op.drop_table('kas_ledger')
    op.drop_table('auth_user_group')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
